### ISSUE TITLE
Error: Extension point conflict: there is already a status indicator for role undefined

### ISSUE THREAD

**Issue by Kayxue** [howbea/logo-activities#3]
![image](https://github.com/howbea/logo-activities/assets/26020165/4b463ea8-8807-4150-b03c-7da2c14978fc)

Any idea about how to solve this?
OS: Arch Linux
Gnome Version: 45.3

**Comment by howbea** [comment]
Thank you for the report with nice picture. I fixed the issue and uploaded the one.
Test it, please.

**Comment by Kayxue** [comment]
It fixed.
Thanks
